version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - internet
      - appnet
  db:
    image: postgres:15
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: admin1234
      POSTGRES_USER: postgres
      POSTGRES_DB: url_storage
    networks:
      - appnet
    volumes:
          - ./db-data:/var/lib/postgresql/data

networks:
  internet:
    name: internet
    driver: bridge
  appnet:
    name: appnet
    driver: bridge

volumes:
  db-data:
