env: "local" # local, dev, prod, ...
#storage_path: "./storage/storage.db" // использовать для БД sqlite
http_server: # конфигурация http сервера
  address: "app:80"
  timeout: 4s # timeout на чтение запроса и отправку ответа. Время на обработку запроса не ограничено.
  idle_timeout: 30s # время жизни соединения с клеентом
  user: "admin"
  password: "admin"
# подключениt к PostgreSQL
storage:
  host: "db"
  port: "5432"
  database: "url_storage" # dvdrental
  username: "postgres"
  password: "admin1234"